version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.undertow:undertow-websockets-jsr
    versions:
    - 2.2.3.Final
    - 2.2.4.Final
    - 2.2.5.Final
  - dependency-name: io.undertow:undertow-servlet
    versions:
    - 2.2.3.Final
    - 2.2.4.Final
    - 2.2.5.Final
  - dependency-name: io.undertow:undertow-core
    versions:
    - 2.2.3.Final
    - 2.2.4.Final
    - 2.2.5.Final
  - dependency-name: org.jboss:jboss-parent
    versions:
    - "37"
